# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.4.0
          
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: 3.x
        repo-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      run: task build

    - name: Test
      run: task test
    
    - name: Integration test
      run: task integration-test

    - name: Acceptance tests
      run: task acceptance-tests
      
    - name: Lint
      run: task lint
      
    - name: Run
      run: task run
